---

- name: Deploy checker to the current system
  hosts: localhost
  become: true
  roles:
    - name: checker
    - name: check_memory
      check_id: memory
    - name: check_ping
      check_id: ping-google
      check_ping_hostname: google.de
