---
- name: Make sure the jo package is installed
  ansible.builtin.package:
    name: jo

- name: Copy alerta script
  ansible.builtin.template:
    src: alerta.sh.j2
    dest: /etc/checker/notifiers/alerta.sh
    mode: u=rwx,g=x,o=x
