---
- name: Make sure the jo package is installed
  ansible.builtin.package:
    name: jo

- name: Copy alerta script
  ansible.builtin.copy:
    src: alerta.sh
    dest: /etc/checker/notifiers/alerta.sh
    mode: u=rwx,g=rx,o=rx
