---
- name: Make sure the jo package is installed
  ansible.builtin.package:
    name: jo

- name: Copy alerta configuration
  ansible.builtin.template:
    src: alerta.env.j2
    dest: /etc/checker/notify_alerta.env
    mode: '0640'
    owner: root
    group: root

- name: Copy alerta script
  ansible.builtin.copy:
    src: notify-alerta.sh
    dest: /etc/checker/notifiers/alerta.sh
    mode: u=rwx,g=x,o=x
