---

- name: Mount points with checks to be created
  debug:
    msg: "{{ checks_for_disks_mounts }}"

- name: Create disk check for each mount
  ansible.builtin.include_role:
    name: check_disk
  vars:
    check_id: >-
      {{
        'root-disk' if item == '/' else
        'disk-' ~ (item | trim('/') | regex_replace('/', '-'))
      }}
    check_disk_paths:
      - "{{ item }}"
  loop: "{{ checks_for_disks_mounts }}"
