---
- name: Install mail dependencies
  ansible.builtin.package:
    name:
      - mailutils
      - postfix
    state: present

- name: Create email configuration
  ansible.builtin.template:
    src: email.env.j2
    dest: "/etc/checker/notify_email.env"
    mode: '0640'
    owner: root
    group: root

- name: Create email notification script
  ansible.builtin.copy:
    src: /mnt/checker/files/notify-email.sh
    dest: /etc/checker/notifiers/email.sh
    mode: u=rwx,g=x,o=x