---

- name: Create base directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwX,g=rX,o=rX
    owner: root
    group: root
  loop:
    - /etc/checker
    - /etc/checker/checks
    - /etc/checker/notifiers
    - /run/checker

- name: Copy readme files
  ansible.builtin.copy:
    src: dir-readme/
    dest: /etc/checker/
    mode: u=rwX,g=rX,o=rX
    owner: root
    group: root

- name: Copy scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/checker/{{ item }}"
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root
  loop:
    - checker.sh
    - notify.sh

- name: Copy Ansible templates
  ansible.builtin.copy:
    src: systemd/
    dest: /etc/systemd/system/
    mode: u=rwX,g=rX,o=rX
    owner: root
    group: root
  notify:
    - Reload systemd daemon
